# =======================================
# Starship prompt config file
# location: ~/.config
# =======================================


format = """$character$cmd_duration$username$directory $git_branch $python
[‚ù±](bold red)[‚ù±](bold green)[‚ù±](bold blue) 
"""

add_newline = false

[character]
error_symbol = "‚ùå "
success_symbol = ""

[cmd_duration]
min_time = 5_000
format = "took [$duration]($style) "

[directory]
format = "[$path]($style)"
truncation_length = 5
truncation_symbol = "../"

[git_branch]
format = "on [$symbol$branch]($style)"
symbol = "üåø"
style = "bold yellow"

[python]
format = "[$symbol$version]($style)"
symbol = "üêç"
style = "bold green"

[username]
style_user = "bold dimmed blue"
show_always = false
